begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/* // Licensed to Julian Hyde under one or more contributor license // agreements. See the NOTICE file distributed with this work for // additional information regarding copyright ownership. // // Julian Hyde licenses this file to you under the Apache License, // Version 2.0 (the "License"); you may not use this file except in // compliance with the License. You may obtain a copy of the License at: // // http://www.apache.org/licenses/LICENSE-2.0 // // Unless required by applicable law or agreed to in writing, software // distributed under the License is distributed on an "AS IS" BASIS, // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. // See the License for the specific language governing permissions and // limitations under the License. */
end_comment

begin_package
package|package
name|org
operator|.
name|eigenbase
operator|.
name|oj
operator|.
name|stmt
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|*
import|;
end_import

begin_import
import|import
name|java
operator|.
name|sql
operator|.
name|*
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|*
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eigenbase
operator|.
name|rel
operator|.
name|*
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eigenbase
operator|.
name|reltype
operator|.
name|*
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eigenbase
operator|.
name|runtime
operator|.
name|*
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eigenbase
operator|.
name|sql
operator|.
name|*
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eigenbase
operator|.
name|util
operator|.
name|*
import|;
end_import

begin_import
import|import
name|net
operator|.
name|hydromatic
operator|.
name|optiq
operator|.
name|prepare
operator|.
name|Prepare
import|;
end_import

begin_comment
comment|/**  * Refinement of {@link net.hydromatic.optiq.prepare.Prepare.PreparedExplain} for OJ.  */
end_comment

begin_class
specifier|public
class|class
name|PreparedExplanation
extends|extends
name|Prepare
operator|.
name|PreparedExplain
block|{
comment|//~ Instance fields --------------------------------------------------------
comment|//~ Constructors -----------------------------------------------------------
specifier|public
name|PreparedExplanation
parameter_list|(
name|RelDataType
name|rowType
parameter_list|,
name|RelNode
name|rel
parameter_list|,
name|boolean
name|asXml
parameter_list|,
name|SqlExplainLevel
name|detailLevel
parameter_list|)
block|{
name|super
argument_list|(
name|rowType
argument_list|,
name|rel
argument_list|,
name|asXml
argument_list|,
name|detailLevel
argument_list|)
expr_stmt|;
block|}
comment|//~ Methods ----------------------------------------------------------------
specifier|public
name|Object
name|execute
parameter_list|()
block|{
specifier|final
name|String
name|explanation
init|=
name|getCode
argument_list|()
decl_stmt|;
return|return
name|executeStatic
argument_list|(
name|explanation
argument_list|)
return|;
block|}
specifier|public
specifier|static
name|ResultSet
name|executeStatic
parameter_list|(
specifier|final
name|String
name|explanation
parameter_list|)
block|{
specifier|final
name|LineNumberReader
name|lineReader
init|=
operator|new
name|LineNumberReader
argument_list|(
operator|new
name|StringReader
argument_list|(
name|explanation
argument_list|)
argument_list|)
decl_stmt|;
name|Iterator
name|iter
init|=
operator|new
name|Iterator
argument_list|()
block|{
specifier|private
name|String
name|line
decl_stmt|;
specifier|public
name|boolean
name|hasNext
parameter_list|()
block|{
if|if
condition|(
name|line
operator|!=
literal|null
condition|)
block|{
return|return
literal|true
return|;
block|}
try|try
block|{
name|line
operator|=
name|lineReader
operator|.
name|readLine
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|ex
parameter_list|)
block|{
throw|throw
name|Util
operator|.
name|newInternal
argument_list|(
name|ex
argument_list|)
throw|;
block|}
return|return
operator|(
name|line
operator|!=
literal|null
operator|)
return|;
block|}
specifier|public
name|Object
name|next
parameter_list|()
block|{
if|if
condition|(
operator|!
name|hasNext
argument_list|()
condition|)
block|{
return|return
literal|null
return|;
block|}
name|String
name|nextLine
init|=
name|line
decl_stmt|;
name|line
operator|=
literal|null
expr_stmt|;
return|return
name|nextLine
return|;
block|}
specifier|public
name|void
name|remove
parameter_list|()
block|{
throw|throw
operator|new
name|UnsupportedOperationException
argument_list|()
throw|;
block|}
block|}
decl_stmt|;
return|return
name|IteratorResultSet
operator|.
name|create
argument_list|(
name|iter
argument_list|,
operator|new
name|IteratorResultSet
operator|.
name|SingletonColumnGetter
argument_list|()
argument_list|)
return|;
block|}
block|}
end_class

begin_comment
comment|// End PreparedExplanation.java
end_comment

end_unit

