begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to you under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|sql
package|;
end_package

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableList
import|;
end_import

begin_comment
comment|/**  * SqlHopTableFunction implements an operator for hopping.  *  *<p>It allows four parameters:  *  *<ol>  *<li>a table</li>  *<li>a descriptor to provide a watermarked column name from the input table</li>  *<li>an interval parameter to specify the length of window shifting</li>  *<li>an interval parameter to specify the length of window size</li>  *</ol>  */
end_comment

begin_class
specifier|public
class|class
name|SqlHopTableFunction
extends|extends
name|SqlWindowTableFunction
block|{
specifier|public
name|SqlHopTableFunction
parameter_list|()
block|{
name|super
argument_list|(
name|SqlKind
operator|.
name|HOP
operator|.
name|name
argument_list|()
argument_list|,
operator|new
name|OperandMetadataImpl
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|/** Operand type checker for HOP. */
specifier|private
specifier|static
class|class
name|OperandMetadataImpl
extends|extends
name|AbstractOperandMetadata
block|{
name|OperandMetadataImpl
parameter_list|()
block|{
name|super
argument_list|(
name|ImmutableList
operator|.
name|of
argument_list|(
name|PARAM_DATA
argument_list|,
name|PARAM_TIMECOL
argument_list|,
name|PARAM_SLIDE
argument_list|,
name|PARAM_SIZE
argument_list|,
name|PARAM_OFFSET
argument_list|)
argument_list|,
literal|4
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|checkOperandTypes
parameter_list|(
name|SqlCallBinding
name|callBinding
parameter_list|,
name|boolean
name|throwOnFailure
parameter_list|)
block|{
if|if
condition|(
operator|!
name|checkTableAndDescriptorOperands
argument_list|(
name|callBinding
argument_list|,
literal|1
argument_list|)
condition|)
block|{
return|return
name|throwValidationSignatureErrorOrReturnFalse
argument_list|(
name|callBinding
argument_list|,
name|throwOnFailure
argument_list|)
return|;
block|}
if|if
condition|(
operator|!
name|checkIntervalOperands
argument_list|(
name|callBinding
argument_list|,
literal|2
argument_list|)
condition|)
block|{
return|return
name|throwValidationSignatureErrorOrReturnFalse
argument_list|(
name|callBinding
argument_list|,
name|throwOnFailure
argument_list|)
return|;
block|}
return|return
literal|true
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|getAllowedSignatures
parameter_list|(
name|SqlOperator
name|op
parameter_list|,
name|String
name|opName
parameter_list|)
block|{
return|return
name|opName
operator|+
literal|"(TABLE table_name, DESCRIPTOR(timecol), "
operator|+
literal|"datetime interval, datetime interval[, datetime interval])"
return|;
block|}
block|}
block|}
end_class

end_unit

