begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to you under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|adapter
operator|.
name|enumerable
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|adapter
operator|.
name|java
operator|.
name|JavaTypeFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|linq4j
operator|.
name|MemoryFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|linq4j
operator|.
name|Ord
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|linq4j
operator|.
name|tree
operator|.
name|BlockBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|linq4j
operator|.
name|tree
operator|.
name|BlockStatement
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|linq4j
operator|.
name|tree
operator|.
name|Expression
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|linq4j
operator|.
name|tree
operator|.
name|Expressions
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|linq4j
operator|.
name|tree
operator|.
name|MemberDeclaration
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|linq4j
operator|.
name|tree
operator|.
name|ParameterExpression
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|linq4j
operator|.
name|tree
operator|.
name|Types
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|plan
operator|.
name|RelOptCluster
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|plan
operator|.
name|RelTraitSet
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|RelCollation
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|RelNode
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|core
operator|.
name|Match
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|type
operator|.
name|RelDataType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|type
operator|.
name|RelDataTypeFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rex
operator|.
name|RexBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rex
operator|.
name|RexCall
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rex
operator|.
name|RexLiteral
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rex
operator|.
name|RexNode
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rex
operator|.
name|RexProgramBuilder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rex
operator|.
name|RexSubQuery
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rex
operator|.
name|RexVisitorImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|runtime
operator|.
name|Enumerables
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|sql
operator|.
name|SqlMatchFunction
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|util
operator|.
name|BuiltInMethod
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|util
operator|.
name|ImmutableBitSet
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|util
operator|.
name|Pair
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|lang
operator|.
name|reflect
operator|.
name|Modifier
import|;
end_import

begin_import
import|import
name|java
operator|.
name|lang
operator|.
name|reflect
operator|.
name|Type
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|SortedSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|function
operator|.
name|Consumer
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|function
operator|.
name|Function
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|function
operator|.
name|Predicate
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|adapter
operator|.
name|enumerable
operator|.
name|EnumUtils
operator|.
name|NO_EXPRS
import|;
end_import

begin_comment
comment|/** Implementation of {@link org.apache.calcite.rel.core.Match} in  * {@link org.apache.calcite.adapter.enumerable.EnumerableConvention enumerable calling convention}. */
end_comment

begin_class
specifier|public
class|class
name|EnumerableMatch
extends|extends
name|Match
implements|implements
name|EnumerableRel
block|{
comment|/**    * Creates an EnumerableMatch.    *    *<p>Use {@link #create} unless you know what you're doing.    */
specifier|public
name|EnumerableMatch
parameter_list|(
name|RelOptCluster
name|cluster
parameter_list|,
name|RelTraitSet
name|traitSet
parameter_list|,
name|RelNode
name|input
parameter_list|,
name|RelDataType
name|rowType
parameter_list|,
name|RexNode
name|pattern
parameter_list|,
name|boolean
name|strictStart
parameter_list|,
name|boolean
name|strictEnd
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|RexNode
argument_list|>
name|patternDefinitions
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|RexNode
argument_list|>
name|measures
parameter_list|,
name|RexNode
name|after
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|?
extends|extends
name|SortedSet
argument_list|<
name|String
argument_list|>
argument_list|>
name|subsets
parameter_list|,
name|boolean
name|allRows
parameter_list|,
name|ImmutableBitSet
name|partitionKeys
parameter_list|,
name|RelCollation
name|orderKeys
parameter_list|,
name|RexNode
name|interval
parameter_list|)
block|{
name|super
argument_list|(
name|cluster
argument_list|,
name|traitSet
argument_list|,
name|input
argument_list|,
name|rowType
argument_list|,
name|pattern
argument_list|,
name|strictStart
argument_list|,
name|strictEnd
argument_list|,
name|patternDefinitions
argument_list|,
name|measures
argument_list|,
name|after
argument_list|,
name|subsets
argument_list|,
name|allRows
argument_list|,
name|partitionKeys
argument_list|,
name|orderKeys
argument_list|,
name|interval
argument_list|)
expr_stmt|;
block|}
comment|/** Creates an EnumerableMatch. */
specifier|public
specifier|static
name|EnumerableMatch
name|create
parameter_list|(
name|RelNode
name|input
parameter_list|,
name|RelDataType
name|rowType
parameter_list|,
name|RexNode
name|pattern
parameter_list|,
name|boolean
name|strictStart
parameter_list|,
name|boolean
name|strictEnd
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|RexNode
argument_list|>
name|patternDefinitions
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|RexNode
argument_list|>
name|measures
parameter_list|,
name|RexNode
name|after
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|?
extends|extends
name|SortedSet
argument_list|<
name|String
argument_list|>
argument_list|>
name|subsets
parameter_list|,
name|boolean
name|allRows
parameter_list|,
name|ImmutableBitSet
name|partitionKeys
parameter_list|,
name|RelCollation
name|orderKeys
parameter_list|,
name|RexNode
name|interval
parameter_list|)
block|{
specifier|final
name|RelOptCluster
name|cluster
init|=
name|input
operator|.
name|getCluster
argument_list|()
decl_stmt|;
specifier|final
name|RelTraitSet
name|traitSet
init|=
name|cluster
operator|.
name|traitSetOf
argument_list|(
name|EnumerableConvention
operator|.
name|INSTANCE
argument_list|)
decl_stmt|;
return|return
operator|new
name|EnumerableMatch
argument_list|(
name|cluster
argument_list|,
name|traitSet
argument_list|,
name|input
argument_list|,
name|rowType
argument_list|,
name|pattern
argument_list|,
name|strictStart
argument_list|,
name|strictEnd
argument_list|,
name|patternDefinitions
argument_list|,
name|measures
argument_list|,
name|after
argument_list|,
name|subsets
argument_list|,
name|allRows
argument_list|,
name|partitionKeys
argument_list|,
name|orderKeys
argument_list|,
name|interval
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|RelNode
name|copy
parameter_list|(
name|RelTraitSet
name|traitSet
parameter_list|,
name|List
argument_list|<
name|RelNode
argument_list|>
name|inputs
parameter_list|)
block|{
return|return
operator|new
name|EnumerableMatch
argument_list|(
name|getCluster
argument_list|()
argument_list|,
name|traitSet
argument_list|,
name|inputs
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|,
name|rowType
argument_list|,
name|pattern
argument_list|,
name|strictStart
argument_list|,
name|strictEnd
argument_list|,
name|patternDefinitions
argument_list|,
name|measures
argument_list|,
name|after
argument_list|,
name|subsets
argument_list|,
name|allRows
argument_list|,
name|partitionKeys
argument_list|,
name|orderKeys
argument_list|,
name|interval
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|EnumerableRel
operator|.
name|Result
name|implement
parameter_list|(
name|EnumerableRelImplementor
name|implementor
parameter_list|,
name|EnumerableRel
operator|.
name|Prefer
name|pref
parameter_list|)
block|{
specifier|final
name|BlockBuilder
name|builder
init|=
operator|new
name|BlockBuilder
argument_list|()
decl_stmt|;
specifier|final
name|EnumerableRel
name|input
init|=
operator|(
name|EnumerableRel
operator|)
name|getInput
argument_list|()
decl_stmt|;
specifier|final
name|Result
name|result
init|=
name|implementor
operator|.
name|visitChild
argument_list|(
name|this
argument_list|,
literal|0
argument_list|,
name|input
argument_list|,
name|pref
argument_list|)
decl_stmt|;
specifier|final
name|PhysType
name|physType
init|=
name|PhysTypeImpl
operator|.
name|of
argument_list|(
name|implementor
operator|.
name|getTypeFactory
argument_list|()
argument_list|,
name|input
operator|.
name|getRowType
argument_list|()
argument_list|,
name|result
operator|.
name|format
argument_list|)
decl_stmt|;
specifier|final
name|Expression
name|inputExp
init|=
name|builder
operator|.
name|append
argument_list|(
literal|"input"
argument_list|,
name|result
operator|.
name|block
argument_list|)
decl_stmt|;
name|PhysType
name|inputPhysType
init|=
name|result
operator|.
name|physType
decl_stmt|;
specifier|final
name|PhysType
name|keyPhysType
init|=
name|inputPhysType
operator|.
name|project
argument_list|(
name|partitionKeys
operator|.
name|asList
argument_list|()
argument_list|,
name|JavaRowFormat
operator|.
name|LIST
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|row_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|inputPhysType
operator|.
name|getJavaRowType
argument_list|()
argument_list|,
literal|"row_"
argument_list|)
decl_stmt|;
specifier|final
name|Expression
name|keySelector_
init|=
name|builder
operator|.
name|append
argument_list|(
literal|"keySelector"
argument_list|,
name|inputPhysType
operator|.
name|generateSelector
argument_list|(
name|row_
argument_list|,
name|partitionKeys
operator|.
name|asList
argument_list|()
argument_list|,
name|keyPhysType
operator|.
name|getFormat
argument_list|()
argument_list|)
argument_list|)
decl_stmt|;
specifier|final
name|RelDataTypeFactory
operator|.
name|Builder
name|typeBuilder
init|=
name|implementor
operator|.
name|getTypeFactory
argument_list|()
operator|.
name|builder
argument_list|()
decl_stmt|;
name|measures
operator|.
name|forEach
argument_list|(
parameter_list|(
name|name
parameter_list|,
name|value
parameter_list|)
lambda|->
name|typeBuilder
operator|.
name|add
argument_list|(
name|name
argument_list|,
name|value
operator|.
name|getType
argument_list|()
argument_list|)
operator|.
name|nullable
argument_list|(
literal|true
argument_list|)
argument_list|)
expr_stmt|;
specifier|final
name|PhysType
name|emitType
init|=
name|PhysTypeImpl
operator|.
name|of
argument_list|(
name|implementor
operator|.
name|getTypeFactory
argument_list|()
argument_list|,
name|typeBuilder
operator|.
name|build
argument_list|()
argument_list|,
name|result
operator|.
name|format
argument_list|)
decl_stmt|;
specifier|final
name|Expression
name|matcher_
init|=
name|implementMatcher
argument_list|(
name|implementor
argument_list|,
name|physType
argument_list|,
name|builder
argument_list|,
name|row_
argument_list|)
decl_stmt|;
specifier|final
name|Expression
name|emitter_
init|=
name|implementEmitter
argument_list|(
name|implementor
argument_list|,
name|emitType
argument_list|,
name|physType
argument_list|)
decl_stmt|;
specifier|final
name|MaxHistoryFutureVisitor
name|visitor
init|=
operator|new
name|MaxHistoryFutureVisitor
argument_list|()
decl_stmt|;
name|patternDefinitions
operator|.
name|values
argument_list|()
operator|.
name|forEach
argument_list|(
name|pd
lambda|->
name|pd
operator|.
name|accept
argument_list|(
name|visitor
argument_list|)
argument_list|)
expr_stmt|;
comment|// Fetch
comment|// Calculate how many steps we need to look back or forward
name|int
name|history
init|=
name|visitor
operator|.
name|getHistory
argument_list|()
decl_stmt|;
name|int
name|future
init|=
name|visitor
operator|.
name|getFuture
argument_list|()
decl_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|return_
argument_list|(
literal|null
argument_list|,
name|Expressions
operator|.
name|call
argument_list|(
name|BuiltInMethod
operator|.
name|MATCH
operator|.
name|method
argument_list|,
name|inputExp
argument_list|,
name|keySelector_
argument_list|,
name|matcher_
argument_list|,
name|emitter_
argument_list|,
name|Expressions
operator|.
name|constant
argument_list|(
name|history
argument_list|)
argument_list|,
name|Expressions
operator|.
name|constant
argument_list|(
name|future
argument_list|)
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|implementor
operator|.
name|result
argument_list|(
name|emitType
argument_list|,
name|builder
operator|.
name|toBlock
argument_list|()
argument_list|)
return|;
block|}
specifier|private
name|Expression
name|implementEmitter
parameter_list|(
name|EnumerableRelImplementor
name|implementor
parameter_list|,
name|PhysType
name|physType
parameter_list|,
name|PhysType
name|inputPhysType
parameter_list|)
block|{
specifier|final
name|ParameterExpression
name|rows_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|Types
operator|.
name|of
argument_list|(
name|List
operator|.
name|class
argument_list|,
name|inputPhysType
operator|.
name|getJavaRowType
argument_list|()
argument_list|)
argument_list|,
literal|"rows"
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|rowStates_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|List
operator|.
name|class
argument_list|,
literal|"rowStates"
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|symbols_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|List
operator|.
name|class
argument_list|,
literal|"symbols"
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|match_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|int
operator|.
name|class
argument_list|,
literal|"match"
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|consumer_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|Consumer
operator|.
name|class
argument_list|,
literal|"consumer"
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|i_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|int
operator|.
name|class
argument_list|,
literal|"i"
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|row_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|inputPhysType
operator|.
name|getJavaRowType
argument_list|()
argument_list|,
literal|"row"
argument_list|)
decl_stmt|;
specifier|final
name|BlockBuilder
name|builder2
init|=
operator|new
name|BlockBuilder
argument_list|()
decl_stmt|;
comment|// Add loop variable initialization
name|builder2
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|declare
argument_list|(
literal|0
argument_list|,
name|row_
argument_list|,
name|EnumUtils
operator|.
name|convert
argument_list|(
name|Expressions
operator|.
name|call
argument_list|(
name|rows_
argument_list|,
name|BuiltInMethod
operator|.
name|LIST_GET
operator|.
name|method
argument_list|,
name|i_
argument_list|)
argument_list|,
name|inputPhysType
operator|.
name|getJavaRowType
argument_list|()
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|RexBuilder
name|rexBuilder
init|=
operator|new
name|RexBuilder
argument_list|(
name|implementor
operator|.
name|getTypeFactory
argument_list|()
argument_list|)
decl_stmt|;
name|RexProgramBuilder
name|rexProgramBuilder
init|=
operator|new
name|RexProgramBuilder
argument_list|(
name|inputPhysType
operator|.
name|getRowType
argument_list|()
argument_list|,
name|rexBuilder
argument_list|)
decl_stmt|;
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|String
argument_list|,
name|RexNode
argument_list|>
name|entry
range|:
name|measures
operator|.
name|entrySet
argument_list|()
control|)
block|{
name|rexProgramBuilder
operator|.
name|addProject
argument_list|(
name|entry
operator|.
name|getValue
argument_list|()
argument_list|,
name|entry
operator|.
name|getKey
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|final
name|RexToLixTranslator
name|translator
init|=
name|RexToLixTranslator
operator|.
name|forAggregation
argument_list|(
operator|(
name|JavaTypeFactory
operator|)
name|getCluster
argument_list|()
operator|.
name|getTypeFactory
argument_list|()
argument_list|,
name|builder2
argument_list|,
operator|new
name|PassedRowsInputGetter
argument_list|(
name|row_
argument_list|,
name|rows_
argument_list|,
name|inputPhysType
argument_list|)
argument_list|,
name|implementor
operator|.
name|getConformance
argument_list|()
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|result_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|physType
operator|.
name|getJavaRowType
argument_list|()
argument_list|)
decl_stmt|;
name|builder2
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|declare
argument_list|(
name|Modifier
operator|.
name|FINAL
argument_list|,
name|result_
argument_list|,
name|Expressions
operator|.
name|new_
argument_list|(
name|physType
operator|.
name|getJavaRowType
argument_list|()
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|Ord
operator|.
name|forEach
argument_list|(
name|measures
operator|.
name|values
argument_list|()
argument_list|,
parameter_list|(
name|measure
parameter_list|,
name|i
parameter_list|)
lambda|->
name|builder2
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|statement
argument_list|(
name|Expressions
operator|.
name|assign
argument_list|(
name|physType
operator|.
name|fieldReference
argument_list|(
name|result_
argument_list|,
name|i
argument_list|)
argument_list|,
name|implementMeasure
argument_list|(
name|translator
argument_list|,
name|rows_
argument_list|,
name|symbols_
argument_list|,
name|i_
argument_list|,
name|row_
argument_list|,
name|measure
argument_list|)
argument_list|)
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|builder2
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|statement
argument_list|(
name|Expressions
operator|.
name|call
argument_list|(
name|consumer_
argument_list|,
name|BuiltInMethod
operator|.
name|CONSUMER_ACCEPT
operator|.
name|method
argument_list|,
name|result_
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
specifier|final
name|BlockBuilder
name|builder
init|=
operator|new
name|BlockBuilder
argument_list|()
decl_stmt|;
comment|// Loop Length
comment|// we have to use an explicit for (int i = ...) loop, as we need to know later
comment|// which of the matched rows are already passed (in MatchUtils), so foreach cannot be used
name|builder
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|for_
argument_list|(
name|Expressions
operator|.
name|declare
argument_list|(
literal|0
argument_list|,
name|i_
argument_list|,
name|Expressions
operator|.
name|constant
argument_list|(
literal|0
argument_list|)
argument_list|)
argument_list|,
name|Expressions
operator|.
name|lessThan
argument_list|(
name|i_
argument_list|,
name|Expressions
operator|.
name|call
argument_list|(
name|rows_
argument_list|,
name|BuiltInMethod
operator|.
name|COLLECTION_SIZE
operator|.
name|method
argument_list|)
argument_list|)
argument_list|,
name|Expressions
operator|.
name|preIncrementAssign
argument_list|(
name|i_
argument_list|)
argument_list|,
name|builder2
operator|.
name|toBlock
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|Expressions
operator|.
name|new_
argument_list|(
name|Types
operator|.
name|of
argument_list|(
name|Enumerables
operator|.
name|Emitter
operator|.
name|class
argument_list|)
argument_list|,
name|NO_EXPRS
argument_list|,
name|Expressions
operator|.
name|list
argument_list|(
name|EnumUtils
operator|.
name|overridingMethodDecl
argument_list|(
name|BuiltInMethod
operator|.
name|EMITTER_EMIT
operator|.
name|method
argument_list|,
name|ImmutableList
operator|.
name|of
argument_list|(
name|rows_
argument_list|,
name|rowStates_
argument_list|,
name|symbols_
argument_list|,
name|match_
argument_list|,
name|consumer_
argument_list|)
argument_list|,
name|builder
operator|.
name|toBlock
argument_list|()
argument_list|)
argument_list|)
argument_list|)
return|;
block|}
specifier|private
name|Expression
name|implementMeasure
parameter_list|(
name|RexToLixTranslator
name|translator
parameter_list|,
name|ParameterExpression
name|rows_
parameter_list|,
name|ParameterExpression
name|symbols_
parameter_list|,
name|ParameterExpression
name|i_
parameter_list|,
name|ParameterExpression
name|row_
parameter_list|,
name|RexNode
name|value
parameter_list|)
block|{
specifier|final
name|SqlMatchFunction
name|matchFunction
decl_stmt|;
specifier|final
name|MatchImplementor
name|matchImplementor
decl_stmt|;
switch|switch
condition|(
name|value
operator|.
name|getKind
argument_list|()
condition|)
block|{
case|case
name|LAST
case|:
case|case
name|PREV
case|:
case|case
name|CLASSIFIER
case|:
name|matchFunction
operator|=
operator|(
name|SqlMatchFunction
operator|)
operator|(
operator|(
name|RexCall
operator|)
name|value
operator|)
operator|.
name|getOperator
argument_list|()
expr_stmt|;
name|matchImplementor
operator|=
name|RexImpTable
operator|.
name|INSTANCE
operator|.
name|get
argument_list|(
name|matchFunction
argument_list|)
expr_stmt|;
comment|// Work with the implementor
return|return
name|matchImplementor
operator|.
name|implement
argument_list|(
name|translator
argument_list|,
operator|(
name|RexCall
operator|)
name|value
argument_list|,
name|row_
argument_list|,
name|rows_
argument_list|,
name|symbols_
argument_list|,
name|i_
argument_list|)
return|;
case|case
name|RUNNING
case|:
case|case
name|FINAL
case|:
comment|// See [CALCITE-3341], this should be changed a bit, to implement
comment|// FINAL behavior
specifier|final
name|List
argument_list|<
name|RexNode
argument_list|>
name|operands
init|=
operator|(
operator|(
name|RexCall
operator|)
name|value
operator|)
operator|.
name|getOperands
argument_list|()
decl_stmt|;
assert|assert
name|operands
operator|.
name|size
argument_list|()
operator|==
literal|1
assert|;
switch|switch
condition|(
name|operands
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|.
name|getKind
argument_list|()
condition|)
block|{
case|case
name|LAST
case|:
case|case
name|PREV
case|:
case|case
name|CLASSIFIER
case|:
specifier|final
name|RexCall
name|call
init|=
operator|(
name|RexCall
operator|)
name|operands
operator|.
name|get
argument_list|(
literal|0
argument_list|)
decl_stmt|;
name|matchFunction
operator|=
operator|(
name|SqlMatchFunction
operator|)
name|call
operator|.
name|getOperator
argument_list|()
expr_stmt|;
name|matchImplementor
operator|=
name|RexImpTable
operator|.
name|INSTANCE
operator|.
name|get
argument_list|(
name|matchFunction
argument_list|)
expr_stmt|;
comment|// Work with the implementor
operator|(
operator|(
name|PassedRowsInputGetter
operator|)
name|translator
operator|.
name|inputGetter
operator|)
operator|.
name|setIndex
argument_list|(
literal|null
argument_list|)
expr_stmt|;
return|return
name|matchImplementor
operator|.
name|implement
argument_list|(
name|translator
argument_list|,
name|call
argument_list|,
name|row_
argument_list|,
name|rows_
argument_list|,
name|symbols_
argument_list|,
name|i_
argument_list|)
return|;
default|default:
break|break;
block|}
return|return
name|translator
operator|.
name|translate
argument_list|(
name|operands
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
return|;
default|default:
return|return
name|translator
operator|.
name|translate
argument_list|(
name|value
argument_list|)
return|;
block|}
block|}
specifier|private
name|Expression
name|implementMatcher
parameter_list|(
name|EnumerableRelImplementor
name|implementor
parameter_list|,
name|PhysType
name|physType
parameter_list|,
name|BlockBuilder
name|builder
parameter_list|,
name|ParameterExpression
name|row_
parameter_list|)
block|{
specifier|final
name|Expression
name|patternBuilder_
init|=
name|builder
operator|.
name|append
argument_list|(
literal|"patternBuilder"
argument_list|,
name|Expressions
operator|.
name|call
argument_list|(
name|BuiltInMethod
operator|.
name|PATTERN_BUILDER
operator|.
name|method
argument_list|)
argument_list|)
decl_stmt|;
specifier|final
name|Expression
name|automaton_
init|=
name|builder
operator|.
name|append
argument_list|(
literal|"automaton"
argument_list|,
name|Expressions
operator|.
name|call
argument_list|(
name|implementPattern
argument_list|(
name|patternBuilder_
argument_list|,
name|pattern
argument_list|)
argument_list|,
name|BuiltInMethod
operator|.
name|PATTERN_TO_AUTOMATON
operator|.
name|method
argument_list|)
argument_list|)
decl_stmt|;
name|Expression
name|matcherBuilder_
init|=
name|builder
operator|.
name|append
argument_list|(
literal|"matcherBuilder"
argument_list|,
name|Expressions
operator|.
name|call
argument_list|(
name|BuiltInMethod
operator|.
name|MATCHER_BUILDER
operator|.
name|method
argument_list|,
name|automaton_
argument_list|)
argument_list|)
decl_stmt|;
specifier|final
name|BlockBuilder
name|builder2
init|=
operator|new
name|BlockBuilder
argument_list|()
decl_stmt|;
comment|// Wrap a MemoryEnumerable around
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|String
argument_list|,
name|RexNode
argument_list|>
name|entry
range|:
name|patternDefinitions
operator|.
name|entrySet
argument_list|()
control|)
block|{
comment|// Translate REX to Expressions
name|RexBuilder
name|rexBuilder
init|=
operator|new
name|RexBuilder
argument_list|(
name|implementor
operator|.
name|getTypeFactory
argument_list|()
argument_list|)
decl_stmt|;
name|RexProgramBuilder
name|rexProgramBuilder
init|=
operator|new
name|RexProgramBuilder
argument_list|(
name|physType
operator|.
name|getRowType
argument_list|()
argument_list|,
name|rexBuilder
argument_list|)
decl_stmt|;
name|rexProgramBuilder
operator|.
name|addCondition
argument_list|(
name|entry
operator|.
name|getValue
argument_list|()
argument_list|)
expr_stmt|;
specifier|final
name|RexToLixTranslator
operator|.
name|InputGetter
name|inputGetter1
init|=
operator|new
name|PrevInputGetter
argument_list|(
name|row_
argument_list|,
name|physType
argument_list|)
decl_stmt|;
specifier|final
name|Expression
name|condition
init|=
name|RexToLixTranslator
operator|.
name|translateCondition
argument_list|(
name|rexProgramBuilder
operator|.
name|getProgram
argument_list|()
argument_list|,
operator|(
name|JavaTypeFactory
operator|)
name|getCluster
argument_list|()
operator|.
name|getTypeFactory
argument_list|()
argument_list|,
name|builder2
argument_list|,
name|inputGetter1
argument_list|,
name|implementor
operator|.
name|allCorrelateVariables
argument_list|,
name|implementor
operator|.
name|getConformance
argument_list|()
argument_list|)
decl_stmt|;
name|builder2
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|return_
argument_list|(
literal|null
argument_list|,
name|condition
argument_list|)
argument_list|)
expr_stmt|;
specifier|final
name|Expression
name|predicate_
init|=
name|implementPredicate
argument_list|(
name|physType
argument_list|,
name|row_
argument_list|,
name|builder2
operator|.
name|toBlock
argument_list|()
argument_list|)
decl_stmt|;
name|matcherBuilder_
operator|=
name|Expressions
operator|.
name|call
argument_list|(
name|matcherBuilder_
argument_list|,
name|BuiltInMethod
operator|.
name|MATCHER_BUILDER_ADD
operator|.
name|method
argument_list|,
name|Expressions
operator|.
name|constant
argument_list|(
name|entry
operator|.
name|getKey
argument_list|()
argument_list|)
argument_list|,
name|predicate_
argument_list|)
expr_stmt|;
block|}
return|return
name|builder
operator|.
name|append
argument_list|(
literal|"matcher"
argument_list|,
name|Expressions
operator|.
name|call
argument_list|(
name|matcherBuilder_
argument_list|,
name|BuiltInMethod
operator|.
name|MATCHER_BUILDER_BUILD
operator|.
name|method
argument_list|)
argument_list|)
return|;
block|}
comment|/** Generates code for a predicate. */
specifier|private
name|Expression
name|implementPredicate
parameter_list|(
name|PhysType
name|physType
parameter_list|,
name|ParameterExpression
name|rows_
parameter_list|,
name|BlockStatement
name|body
parameter_list|)
block|{
specifier|final
name|List
argument_list|<
name|MemberDeclaration
argument_list|>
name|memberDeclarations
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
name|ParameterExpression
name|row_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|Types
operator|.
name|of
argument_list|(
name|MemoryFactory
operator|.
name|Memory
operator|.
name|class
argument_list|,
name|physType
operator|.
name|getJavaRowType
argument_list|()
argument_list|)
argument_list|,
literal|"row_"
argument_list|)
decl_stmt|;
name|Expressions
operator|.
name|assign
argument_list|(
name|row_
argument_list|,
name|Expressions
operator|.
name|call
argument_list|(
name|rows_
argument_list|,
name|BuiltInMethod
operator|.
name|MEMORY_GET0
operator|.
name|method
argument_list|)
argument_list|)
expr_stmt|;
comment|// Implement the Predicate here based on the pattern definition
comment|// Add a predicate method:
comment|//
comment|//   public boolean test(E row, List<E> rows) {
comment|//     return ...;
comment|//   }
name|memberDeclarations
operator|.
name|add
argument_list|(
name|EnumUtils
operator|.
name|overridingMethodDecl
argument_list|(
name|BuiltInMethod
operator|.
name|PREDICATE_TEST
operator|.
name|method
argument_list|,
name|ImmutableList
operator|.
name|of
argument_list|(
name|row_
argument_list|)
argument_list|,
name|body
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|EnumerableRules
operator|.
name|BRIDGE_METHODS
condition|)
block|{
comment|// Add a bridge method:
comment|//
comment|//   public boolean test(Object row, Object rows) {
comment|//     return this.test(row, (List) rows);
comment|//   }
specifier|final
name|ParameterExpression
name|row0_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|Object
operator|.
name|class
argument_list|,
literal|"row"
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|rowsO_
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|Object
operator|.
name|class
argument_list|,
literal|"rows"
argument_list|)
decl_stmt|;
name|BlockBuilder
name|bridgeBody
init|=
operator|new
name|BlockBuilder
argument_list|()
decl_stmt|;
name|bridgeBody
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|return_
argument_list|(
literal|null
argument_list|,
name|Expressions
operator|.
name|call
argument_list|(
name|Expressions
operator|.
name|parameter
argument_list|(
name|Comparable
operator|.
name|class
argument_list|,
literal|"this"
argument_list|)
argument_list|,
name|BuiltInMethod
operator|.
name|PREDICATE_TEST
operator|.
name|method
argument_list|,
name|Expressions
operator|.
name|convert_
argument_list|(
name|row0_
argument_list|,
name|Types
operator|.
name|of
argument_list|(
name|MemoryFactory
operator|.
name|Memory
operator|.
name|class
argument_list|,
name|physType
operator|.
name|getJavaRowType
argument_list|()
argument_list|)
argument_list|)
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|memberDeclarations
operator|.
name|add
argument_list|(
name|EnumUtils
operator|.
name|overridingMethodDecl
argument_list|(
name|BuiltInMethod
operator|.
name|PREDICATE_TEST
operator|.
name|method
argument_list|,
name|ImmutableList
operator|.
name|of
argument_list|(
name|row0_
argument_list|)
argument_list|,
name|bridgeBody
operator|.
name|toBlock
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
return|return
name|Expressions
operator|.
name|new_
argument_list|(
name|Types
operator|.
name|of
argument_list|(
name|Predicate
operator|.
name|class
argument_list|)
argument_list|,
name|NO_EXPRS
argument_list|,
name|memberDeclarations
argument_list|)
return|;
block|}
comment|/** Generates code for a pattern.    *    *<p>For example, for the pattern {@code (A B)}, generates    * {@code patternBuilder.symbol("A").symbol("B").seq()}. */
specifier|private
name|Expression
name|implementPattern
parameter_list|(
name|Expression
name|patternBuilder_
parameter_list|,
name|RexNode
name|pattern
parameter_list|)
block|{
switch|switch
condition|(
name|pattern
operator|.
name|getKind
argument_list|()
condition|)
block|{
case|case
name|LITERAL
case|:
specifier|final
name|String
name|symbol
init|=
operator|(
operator|(
name|RexLiteral
operator|)
name|pattern
operator|)
operator|.
name|getValueAs
argument_list|(
name|String
operator|.
name|class
argument_list|)
decl_stmt|;
return|return
name|Expressions
operator|.
name|call
argument_list|(
name|patternBuilder_
argument_list|,
name|BuiltInMethod
operator|.
name|PATTERN_BUILDER_SYMBOL
operator|.
name|method
argument_list|,
name|Expressions
operator|.
name|constant
argument_list|(
name|symbol
argument_list|)
argument_list|)
return|;
case|case
name|PATTERN_CONCAT
case|:
specifier|final
name|RexCall
name|concat
init|=
operator|(
name|RexCall
operator|)
name|pattern
decl_stmt|;
for|for
control|(
name|Ord
argument_list|<
name|RexNode
argument_list|>
name|operand
range|:
name|Ord
operator|.
name|zip
argument_list|(
name|concat
operator|.
name|operands
argument_list|)
control|)
block|{
name|patternBuilder_
operator|=
name|implementPattern
argument_list|(
name|patternBuilder_
argument_list|,
name|operand
operator|.
name|e
argument_list|)
expr_stmt|;
if|if
condition|(
name|operand
operator|.
name|i
operator|>
literal|0
condition|)
block|{
name|patternBuilder_
operator|=
name|Expressions
operator|.
name|call
argument_list|(
name|patternBuilder_
argument_list|,
name|BuiltInMethod
operator|.
name|PATTERN_BUILDER_SEQ
operator|.
name|method
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|patternBuilder_
return|;
default|default:
throw|throw
operator|new
name|AssertionError
argument_list|(
literal|"unknown kind: "
operator|+
name|pattern
argument_list|)
throw|;
block|}
block|}
comment|/**    * Visitor that finds out how much "history" we need in the past and future.    */
specifier|private
specifier|static
class|class
name|MaxHistoryFutureVisitor
extends|extends
name|RexVisitorImpl
argument_list|<
name|Void
argument_list|>
block|{
specifier|private
name|int
name|history
decl_stmt|;
specifier|private
name|int
name|future
decl_stmt|;
specifier|protected
name|MaxHistoryFutureVisitor
parameter_list|()
block|{
name|super
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
specifier|public
name|int
name|getHistory
parameter_list|()
block|{
return|return
name|history
return|;
block|}
specifier|public
name|int
name|getFuture
parameter_list|()
block|{
return|return
name|future
return|;
block|}
annotation|@
name|Override
specifier|public
name|Void
name|visitCall
parameter_list|(
name|RexCall
name|call
parameter_list|)
block|{
name|call
operator|.
name|operands
operator|.
name|forEach
argument_list|(
name|o
lambda|->
name|o
operator|.
name|accept
argument_list|(
name|this
argument_list|)
argument_list|)
expr_stmt|;
specifier|final
name|RexLiteral
name|operand
decl_stmt|;
switch|switch
condition|(
name|call
operator|.
name|op
operator|.
name|kind
condition|)
block|{
case|case
name|PREV
case|:
name|operand
operator|=
operator|(
name|RexLiteral
operator|)
name|call
operator|.
name|getOperands
argument_list|()
operator|.
name|get
argument_list|(
literal|1
argument_list|)
expr_stmt|;
specifier|final
name|int
name|prev
init|=
name|operand
operator|.
name|getValueAs
argument_list|(
name|Integer
operator|.
name|class
argument_list|)
decl_stmt|;
name|this
operator|.
name|history
operator|=
name|Math
operator|.
name|max
argument_list|(
name|this
operator|.
name|history
argument_list|,
name|prev
argument_list|)
expr_stmt|;
break|break;
case|case
name|NEXT
case|:
name|operand
operator|=
operator|(
name|RexLiteral
operator|)
name|call
operator|.
name|getOperands
argument_list|()
operator|.
name|get
argument_list|(
literal|1
argument_list|)
expr_stmt|;
specifier|final
name|int
name|next
init|=
name|operand
operator|.
name|getValueAs
argument_list|(
name|Integer
operator|.
name|class
argument_list|)
decl_stmt|;
name|this
operator|.
name|future
operator|=
name|Math
operator|.
name|max
argument_list|(
name|this
operator|.
name|future
argument_list|,
name|next
argument_list|)
expr_stmt|;
break|break;
default|default:
break|break;
block|}
return|return
literal|null
return|;
block|}
annotation|@
name|Override
specifier|public
name|Void
name|visitSubQuery
parameter_list|(
name|RexSubQuery
name|subQuery
parameter_list|)
block|{
return|return
literal|null
return|;
block|}
block|}
comment|/**    * A special Getter that is able to return a field from a list of objects.    */
specifier|static
class|class
name|PassedRowsInputGetter
implements|implements
name|RexToLixTranslator
operator|.
name|InputGetter
block|{
specifier|private
name|Expression
name|index
decl_stmt|;
specifier|private
specifier|final
name|ParameterExpression
name|row
decl_stmt|;
specifier|private
specifier|final
name|ParameterExpression
name|passedRows
decl_stmt|;
specifier|private
specifier|final
name|Function
argument_list|<
name|Expression
argument_list|,
name|RexToLixTranslator
operator|.
name|InputGetter
argument_list|>
name|generator
decl_stmt|;
specifier|private
specifier|final
name|PhysType
name|physType
decl_stmt|;
name|PassedRowsInputGetter
parameter_list|(
name|ParameterExpression
name|row
parameter_list|,
name|ParameterExpression
name|passedRows
parameter_list|,
name|PhysType
name|physType
parameter_list|)
block|{
name|this
operator|.
name|row
operator|=
name|row
expr_stmt|;
name|this
operator|.
name|passedRows
operator|=
name|passedRows
expr_stmt|;
name|generator
operator|=
name|e
lambda|->
operator|new
name|RexToLixTranslator
operator|.
name|InputGetterImpl
argument_list|(
name|Collections
operator|.
name|singletonList
argument_list|(
name|Pair
operator|.
name|of
argument_list|(
name|e
argument_list|,
name|physType
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|this
operator|.
name|physType
operator|=
name|physType
expr_stmt|;
block|}
name|void
name|setIndex
parameter_list|(
name|Expression
name|index
parameter_list|)
block|{
name|this
operator|.
name|index
operator|=
name|index
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|Expression
name|field
parameter_list|(
name|BlockBuilder
name|list
parameter_list|,
name|int
name|index
parameter_list|,
name|Type
name|storageType
parameter_list|)
block|{
if|if
condition|(
name|this
operator|.
name|index
operator|==
literal|null
condition|)
block|{
return|return
name|generator
operator|.
name|apply
argument_list|(
name|this
operator|.
name|row
argument_list|)
operator|.
name|field
argument_list|(
name|list
argument_list|,
name|index
argument_list|,
name|storageType
argument_list|)
return|;
block|}
return|return
name|Expressions
operator|.
name|condition
argument_list|(
name|Expressions
operator|.
name|greaterThanOrEqual
argument_list|(
name|this
operator|.
name|index
argument_list|,
name|Expressions
operator|.
name|constant
argument_list|(
literal|0
argument_list|)
argument_list|)
argument_list|,
name|generator
operator|.
name|apply
argument_list|(
name|EnumUtils
operator|.
name|convert
argument_list|(
name|Expressions
operator|.
name|call
argument_list|(
name|this
operator|.
name|passedRows
argument_list|,
name|BuiltInMethod
operator|.
name|LIST_GET
operator|.
name|method
argument_list|,
name|this
operator|.
name|index
argument_list|)
argument_list|,
name|physType
operator|.
name|getJavaRowType
argument_list|()
argument_list|)
argument_list|)
operator|.
name|field
argument_list|(
name|list
argument_list|,
name|index
argument_list|,
name|storageType
argument_list|)
argument_list|,
name|Expressions
operator|.
name|constant
argument_list|(
literal|null
argument_list|)
argument_list|)
return|;
block|}
block|}
comment|/**    * A special Getter that "interchanges" the PREV and the field call.    */
specifier|static
class|class
name|PrevInputGetter
implements|implements
name|RexToLixTranslator
operator|.
name|InputGetter
block|{
specifier|private
name|Expression
name|offset
decl_stmt|;
specifier|private
specifier|final
name|ParameterExpression
name|row
decl_stmt|;
specifier|private
specifier|final
name|Function
argument_list|<
name|Expression
argument_list|,
name|RexToLixTranslator
operator|.
name|InputGetter
argument_list|>
name|generator
decl_stmt|;
specifier|private
specifier|final
name|PhysType
name|physType
decl_stmt|;
name|PrevInputGetter
parameter_list|(
name|ParameterExpression
name|row
parameter_list|,
name|PhysType
name|physType
parameter_list|)
block|{
name|this
operator|.
name|row
operator|=
name|row
expr_stmt|;
name|generator
operator|=
name|e
lambda|->
operator|new
name|RexToLixTranslator
operator|.
name|InputGetterImpl
argument_list|(
name|Collections
operator|.
name|singletonList
argument_list|(
name|Pair
operator|.
name|of
argument_list|(
name|e
argument_list|,
name|physType
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|this
operator|.
name|physType
operator|=
name|physType
expr_stmt|;
block|}
name|void
name|setOffset
parameter_list|(
name|Expression
name|offset
parameter_list|)
block|{
name|this
operator|.
name|offset
operator|=
name|offset
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|Expression
name|field
parameter_list|(
name|BlockBuilder
name|list
parameter_list|,
name|int
name|index
parameter_list|,
name|Type
name|storageType
parameter_list|)
block|{
specifier|final
name|ParameterExpression
name|row
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|physType
operator|.
name|getJavaRowType
argument_list|()
argument_list|)
decl_stmt|;
specifier|final
name|ParameterExpression
name|tmp
init|=
name|Expressions
operator|.
name|parameter
argument_list|(
name|Object
operator|.
name|class
argument_list|)
decl_stmt|;
name|list
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|declare
argument_list|(
literal|0
argument_list|,
name|tmp
argument_list|,
name|Expressions
operator|.
name|call
argument_list|(
name|this
operator|.
name|row
argument_list|,
name|BuiltInMethod
operator|.
name|MEMORY_GET1
operator|.
name|method
argument_list|,
name|offset
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|list
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|declare
argument_list|(
literal|0
argument_list|,
name|row
argument_list|,
name|Expressions
operator|.
name|convert_
argument_list|(
name|tmp
argument_list|,
name|physType
operator|.
name|getJavaRowType
argument_list|()
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
comment|// Add return statement if here is a null!
name|list
operator|.
name|add
argument_list|(
name|Expressions
operator|.
name|ifThen
argument_list|(
name|Expressions
operator|.
name|equal
argument_list|(
name|tmp
argument_list|,
name|Expressions
operator|.
name|constant
argument_list|(
literal|null
argument_list|)
argument_list|)
argument_list|,
name|Expressions
operator|.
name|return_
argument_list|(
literal|null
argument_list|,
name|Expressions
operator|.
name|constant
argument_list|(
literal|false
argument_list|)
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|generator
operator|.
name|apply
argument_list|(
name|row
argument_list|)
operator|.
name|field
argument_list|(
name|list
argument_list|,
name|index
argument_list|,
name|storageType
argument_list|)
return|;
block|}
block|}
block|}
end_class

end_unit

