begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to you under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|sql
operator|.
name|validate
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|type
operator|.
name|RelDataType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|type
operator|.
name|RelDataTypeFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|sql
operator|.
name|SqlNode
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|util
operator|.
name|Util
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Preconditions
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_comment
comment|/** Namespace based on a schema.  *  *<p>The visible names are tables and sub-schemas.  */
end_comment

begin_class
class|class
name|SchemaNamespace
extends|extends
name|AbstractNamespace
block|{
comment|/** The path of this schema. */
specifier|private
specifier|final
name|ImmutableList
argument_list|<
name|String
argument_list|>
name|names
decl_stmt|;
comment|/** Creates a SchemaNamespace. */
name|SchemaNamespace
parameter_list|(
name|SqlValidatorImpl
name|validator
parameter_list|,
name|ImmutableList
argument_list|<
name|String
argument_list|>
name|names
parameter_list|)
block|{
name|super
argument_list|(
name|validator
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|this
operator|.
name|names
operator|=
name|Preconditions
operator|.
name|checkNotNull
argument_list|(
name|names
argument_list|)
expr_stmt|;
block|}
specifier|protected
name|RelDataType
name|validateImpl
parameter_list|(
name|RelDataType
name|targetRowType
parameter_list|)
block|{
specifier|final
name|RelDataTypeFactory
operator|.
name|FieldInfoBuilder
name|builder
init|=
name|validator
operator|.
name|getTypeFactory
argument_list|()
operator|.
name|builder
argument_list|()
decl_stmt|;
for|for
control|(
name|SqlMoniker
name|moniker
range|:
name|validator
operator|.
name|catalogReader
operator|.
name|getAllSchemaObjectNames
argument_list|(
name|names
argument_list|)
control|)
block|{
specifier|final
name|List
argument_list|<
name|String
argument_list|>
name|names1
init|=
name|moniker
operator|.
name|getFullyQualifiedNames
argument_list|()
decl_stmt|;
specifier|final
name|SqlValidatorTable
name|table
init|=
name|validator
operator|.
name|catalogReader
operator|.
name|getTable
argument_list|(
name|names1
argument_list|)
decl_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|Util
operator|.
name|last
argument_list|(
name|names1
argument_list|)
argument_list|,
name|table
operator|.
name|getRowType
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|builder
operator|.
name|build
argument_list|()
return|;
block|}
specifier|public
name|SqlNode
name|getNode
parameter_list|()
block|{
return|return
literal|null
return|;
block|}
block|}
end_class

begin_comment
comment|// End SchemaNamespace.java
end_comment

end_unit

