begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/* // Licensed to Julian Hyde under one or more contributor license // agreements. See the NOTICE file distributed with this work for // additional information regarding copyright ownership. // // Julian Hyde licenses this file to you under the Apache License, // Version 2.0 (the "License"); you may not use this file except in // compliance with the License. You may obtain a copy of the License at: // // http://www.apache.org/licenses/LICENSE-2.0 // // Unless required by applicable law or agreed to in writing, software // distributed under the License is distributed on an "AS IS" BASIS, // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. // See the License for the specific language governing permissions and // limitations under the License. */
end_comment

begin_package
package|package
name|org
operator|.
name|eigenbase
operator|.
name|rel
operator|.
name|rules
package|;
end_package

begin_import
import|import
name|org
operator|.
name|eigenbase
operator|.
name|rel
operator|.
name|*
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eigenbase
operator|.
name|relopt
operator|.
name|*
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eigenbase
operator|.
name|rex
operator|.
name|*
import|;
end_import

begin_comment
comment|/**  * PushFilterPastProjectRule implements the rule for pushing a {@link FilterRel}  * past a {@link ProjectRel}.  */
end_comment

begin_class
specifier|public
class|class
name|PushFilterPastProjectRule
extends|extends
name|RelOptRule
block|{
specifier|public
specifier|static
specifier|final
name|PushFilterPastProjectRule
name|instance
init|=
operator|new
name|PushFilterPastProjectRule
argument_list|()
decl_stmt|;
comment|//~ Constructors -----------------------------------------------------------
comment|/**      * Creates a PushFilterPastProjectRule.      */
specifier|private
name|PushFilterPastProjectRule
parameter_list|()
block|{
name|super
argument_list|(
name|some
argument_list|(
name|FilterRel
operator|.
name|class
argument_list|,
name|any
argument_list|(
name|ProjectRel
operator|.
name|class
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|//~ Methods ----------------------------------------------------------------
comment|// implement RelOptRule
specifier|public
name|void
name|onMatch
parameter_list|(
name|RelOptRuleCall
name|call
parameter_list|)
block|{
name|FilterRel
name|filterRel
init|=
name|call
operator|.
name|rel
argument_list|(
literal|0
argument_list|)
decl_stmt|;
name|ProjectRel
name|projRel
init|=
name|call
operator|.
name|rel
argument_list|(
literal|1
argument_list|)
decl_stmt|;
comment|// convert the filter to one that references the child of the project
name|RexNode
name|newCondition
init|=
name|RelOptUtil
operator|.
name|pushFilterPastProject
argument_list|(
name|filterRel
operator|.
name|getCondition
argument_list|()
argument_list|,
name|projRel
argument_list|)
decl_stmt|;
name|FilterRel
name|newFilterRel
init|=
operator|new
name|FilterRel
argument_list|(
name|filterRel
operator|.
name|getCluster
argument_list|()
argument_list|,
name|projRel
operator|.
name|getChild
argument_list|()
argument_list|,
name|newCondition
argument_list|)
decl_stmt|;
name|ProjectRel
name|newProjRel
init|=
operator|(
name|ProjectRel
operator|)
name|CalcRel
operator|.
name|createProject
argument_list|(
name|newFilterRel
argument_list|,
name|projRel
operator|.
name|getNamedProjects
argument_list|()
argument_list|,
literal|false
argument_list|)
decl_stmt|;
name|call
operator|.
name|transformTo
argument_list|(
name|newProjRel
argument_list|)
expr_stmt|;
block|}
block|}
end_class

begin_comment
comment|// End PushFilterPastProjectRule.java
end_comment

end_unit

