begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to you under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|avatica
operator|.
name|remote
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|avatica
operator|.
name|AvaticaSeverity
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|avatica
operator|.
name|remote
operator|.
name|Service
operator|.
name|ErrorResponse
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Objects
import|;
end_import

begin_comment
comment|/**  * A {@link RuntimeException} thrown by Avatica with additional contextual information about  * what happened to cause the Exception.  */
end_comment

begin_class
specifier|public
class|class
name|AvaticaRuntimeException
extends|extends
name|RuntimeException
block|{
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
literal|1L
decl_stmt|;
specifier|private
specifier|final
name|String
name|errorMessage
decl_stmt|;
specifier|private
specifier|final
name|int
name|errorCode
decl_stmt|;
specifier|private
specifier|final
name|String
name|sqlState
decl_stmt|;
specifier|private
specifier|final
name|AvaticaSeverity
name|severity
decl_stmt|;
comment|/**    * Constructs an {@code AvaticaRuntimeException} with no additional information.    *    *<p>It is strongly preferred that the caller invoke    * {@link #AvaticaRuntimeException(String, int, String, AvaticaSeverity)}    * with proper contextual information.    */
specifier|public
name|AvaticaRuntimeException
parameter_list|()
block|{
name|this
argument_list|(
literal|"No additional context on exception"
argument_list|,
name|ErrorResponse
operator|.
name|UNKNOWN_ERROR_CODE
argument_list|,
name|ErrorResponse
operator|.
name|UNKNOWN_SQL_STATE
argument_list|,
name|AvaticaSeverity
operator|.
name|UNKNOWN
argument_list|)
expr_stmt|;
block|}
comment|/**    * Constructs an {@code AvaticaRuntimeException} with the given    * contextual information surrounding the error.    *    * @param errorMessage A human-readable explanation about what happened    * @param errorCode Numeric identifier for error    * @param sqlState 5-character identifier for error    * @param severity Severity    */
specifier|public
name|AvaticaRuntimeException
parameter_list|(
name|String
name|errorMessage
parameter_list|,
name|int
name|errorCode
parameter_list|,
name|String
name|sqlState
parameter_list|,
name|AvaticaSeverity
name|severity
parameter_list|)
block|{
name|this
operator|.
name|errorMessage
operator|=
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|errorMessage
argument_list|)
expr_stmt|;
name|this
operator|.
name|errorCode
operator|=
name|errorCode
expr_stmt|;
name|this
operator|.
name|sqlState
operator|=
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|sqlState
argument_list|)
expr_stmt|;
name|this
operator|.
name|severity
operator|=
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|severity
argument_list|)
expr_stmt|;
block|}
comment|/**    * Returns a human-readable error message.    */
specifier|public
name|String
name|getErrorMessage
parameter_list|()
block|{
return|return
name|errorMessage
return|;
block|}
comment|/**    * Returns a numeric code for this error.    */
specifier|public
name|int
name|getErrorCode
parameter_list|()
block|{
return|return
name|errorCode
return|;
block|}
comment|/**    * Returns the five-character identifier for this error.    */
specifier|public
name|String
name|getSqlState
parameter_list|()
block|{
return|return
name|sqlState
return|;
block|}
comment|/**    * Returns the severity at which this exception is thrown.    */
specifier|public
name|AvaticaSeverity
name|getSeverity
parameter_list|()
block|{
return|return
name|severity
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|toString
parameter_list|()
block|{
name|StringBuilder
name|sb
init|=
operator|new
name|StringBuilder
argument_list|(
literal|64
argument_list|)
decl_stmt|;
return|return
name|sb
operator|.
name|append
argument_list|(
literal|"AvaticaRuntimeException: ["
argument_list|)
operator|.
name|append
argument_list|(
literal|"Messsage: '"
argument_list|)
operator|.
name|append
argument_list|(
name|errorMessage
argument_list|)
operator|.
name|append
argument_list|(
literal|"', "
argument_list|)
operator|.
name|append
argument_list|(
literal|"Error code: '"
argument_list|)
operator|.
name|append
argument_list|(
name|errorCode
argument_list|)
operator|.
name|append
argument_list|(
literal|"', "
argument_list|)
operator|.
name|append
argument_list|(
literal|"SQL State: '"
argument_list|)
operator|.
name|append
argument_list|(
name|sqlState
argument_list|)
operator|.
name|append
argument_list|(
literal|"', "
argument_list|)
operator|.
name|append
argument_list|(
literal|"Severity: '"
argument_list|)
operator|.
name|append
argument_list|(
name|severity
argument_list|)
operator|.
name|append
argument_list|(
literal|"']"
argument_list|)
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
end_class

begin_comment
comment|// End AvaticaRuntimeException.java
end_comment

end_unit

