begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to you under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|hint
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|RelNode
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableList
import|;
end_import

begin_comment
comment|/**  * Strategy to decide if a hint should apply to a relational expression  * by using a series of {@link HintStrategy} rules in a given order.  * If a rule fails, returns false early, else return true.  */
end_comment

begin_class
specifier|public
class|class
name|HintStrategyCascade
implements|implements
name|HintStrategy
block|{
comment|//~ Instance fields --------------------------------------------------------
specifier|private
name|ImmutableList
argument_list|<
name|HintStrategy
argument_list|>
name|strategies
decl_stmt|;
comment|/**    * Creates a HintStrategyCascade from an array of hint strategies.    *    *<p>Make this constructor package-protected intentionally.    * Use {@link HintStrategies#cascade}.</p>    */
name|HintStrategyCascade
parameter_list|(
name|HintStrategy
modifier|...
name|strategies
parameter_list|)
block|{
assert|assert
name|strategies
operator|!=
literal|null
assert|;
assert|assert
name|strategies
operator|.
name|length
operator|>
literal|1
assert|;
for|for
control|(
name|HintStrategy
name|strategy
range|:
name|strategies
control|)
block|{
assert|assert
name|strategy
operator|!=
literal|null
assert|;
block|}
name|this
operator|.
name|strategies
operator|=
name|ImmutableList
operator|.
name|copyOf
argument_list|(
name|strategies
argument_list|)
expr_stmt|;
block|}
comment|//~ Methods ----------------------------------------------------------------
annotation|@
name|Override
specifier|public
name|boolean
name|supportsRel
parameter_list|(
name|RelHint
name|hint
parameter_list|,
name|RelNode
name|rel
parameter_list|)
block|{
for|for
control|(
name|HintStrategy
name|strategy
range|:
name|strategies
control|)
block|{
if|if
condition|(
operator|!
name|strategy
operator|.
name|supportsRel
argument_list|(
name|hint
argument_list|,
name|rel
argument_list|)
condition|)
block|{
return|return
literal|false
return|;
block|}
block|}
return|return
literal|true
return|;
block|}
block|}
end_class

begin_comment
comment|// End HintStrategyCascade.java
end_comment

end_unit

