begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to you under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|adapter
operator|.
name|mongodb
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|test
operator|.
name|MongoAssertions
import|;
end_import

begin_import
import|import
name|com
operator|.
name|github
operator|.
name|fakemongo
operator|.
name|Fongo
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|MongoClient
import|;
end_import

begin_import
import|import
name|com
operator|.
name|mongodb
operator|.
name|client
operator|.
name|MongoDatabase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|rules
operator|.
name|ExternalResource
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Objects
import|;
end_import

begin_comment
comment|/**  * Instantiates a new connection to Fongo (or Mongo) database depending on the  * current profile (unit or integration tests).  *  *<p>By default, this rule is executed as part of a unit test and in-memory database  *<a href="https://github.com/fakemongo/fongo">Fongo</a> is used.  *  *<p>However, if the maven profile is set to {@code IT} (eg. via command line  * {@code $ mvn -Pit install}) this rule will connect to an existing (external)  * Mongo instance ({@code localhost}).  */
end_comment

begin_class
class|class
name|MongoDatabasePolicy
extends|extends
name|ExternalResource
block|{
specifier|private
specifier|static
specifier|final
name|String
name|DB_NAME
init|=
literal|"test"
decl_stmt|;
specifier|private
specifier|final
name|MongoDatabase
name|database
decl_stmt|;
specifier|private
specifier|final
name|MongoClient
name|client
decl_stmt|;
specifier|private
name|MongoDatabasePolicy
parameter_list|(
name|MongoClient
name|client
parameter_list|)
block|{
name|this
operator|.
name|client
operator|=
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|client
argument_list|,
literal|"client"
argument_list|)
expr_stmt|;
name|this
operator|.
name|database
operator|=
name|client
operator|.
name|getDatabase
argument_list|(
name|DB_NAME
argument_list|)
expr_stmt|;
block|}
comment|/**    * Creates an instance based on current maven profile (as defined by {@code -Pit}).    *    * @return new instance of the policy to be used by unit tests    */
specifier|static
name|MongoDatabasePolicy
name|create
parameter_list|()
block|{
specifier|final
name|MongoClient
name|client
decl_stmt|;
if|if
condition|(
name|MongoAssertions
operator|.
name|useMongo
argument_list|()
condition|)
block|{
comment|// use to real client (connects to mongo)
name|client
operator|=
operator|new
name|MongoClient
argument_list|()
expr_stmt|;
block|}
if|else if
condition|(
name|MongoAssertions
operator|.
name|useFongo
argument_list|()
condition|)
block|{
comment|// in-memory DB (fake Mongo)
name|client
operator|=
operator|new
name|Fongo
argument_list|(
name|MongoDatabasePolicy
operator|.
name|class
operator|.
name|getSimpleName
argument_list|()
argument_list|)
operator|.
name|getMongo
argument_list|()
expr_stmt|;
block|}
else|else
block|{
throw|throw
operator|new
name|UnsupportedOperationException
argument_list|(
literal|"I can only connect to Mongo or Fongo instances"
argument_list|)
throw|;
block|}
return|return
operator|new
name|MongoDatabasePolicy
argument_list|(
name|client
argument_list|)
return|;
block|}
name|MongoDatabase
name|database
parameter_list|()
block|{
return|return
name|database
return|;
block|}
annotation|@
name|Override
specifier|protected
name|void
name|after
parameter_list|()
block|{
name|client
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
block|}
end_class

begin_comment
comment|// End MongoDatabasePolicy.java
end_comment

end_unit

