begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/* // Licensed to Julian Hyde under one or more contributor license // agreements. See the NOTICE file distributed with this work for // additional information regarding copyright ownership. // // Julian Hyde licenses this file to you under the Apache License, // Version 2.0 (the "License"); you may not use this file except in // compliance with the License. You may obtain a copy of the License at: // // http://www.apache.org/licenses/LICENSE-2.0 // // Unless required by applicable law or agreed to in writing, software // distributed under the License is distributed on an "AS IS" BASIS, // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. // See the License for the specific language governing permissions and // limitations under the License. */
end_comment

begin_package
package|package
name|net
operator|.
name|hydromatic
operator|.
name|optiq
operator|.
name|impl
operator|.
name|jdbc
package|;
end_package

begin_import
import|import
name|net
operator|.
name|hydromatic
operator|.
name|linq4j
operator|.
name|Enumerator
import|;
end_import

begin_import
import|import
name|net
operator|.
name|hydromatic
operator|.
name|linq4j
operator|.
name|QueryProviderImpl
import|;
end_import

begin_import
import|import
name|net
operator|.
name|hydromatic
operator|.
name|linq4j
operator|.
name|expressions
operator|.
name|Expression
import|;
end_import

begin_import
import|import
name|java
operator|.
name|lang
operator|.
name|reflect
operator|.
name|Type
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|sql
operator|.
name|DataSource
import|;
end_import

begin_comment
comment|/**  * @author jhyde  */
end_comment

begin_class
specifier|public
class|class
name|JdbcQueryProvider
extends|extends
name|QueryProviderImpl
block|{
specifier|private
specifier|final
name|DataSource
name|dataSource
decl_stmt|;
specifier|public
name|JdbcQueryProvider
parameter_list|(
name|DataSource
name|dataSource
parameter_list|)
block|{
name|super
argument_list|()
expr_stmt|;
name|this
operator|.
name|dataSource
operator|=
name|dataSource
expr_stmt|;
block|}
annotation|@
name|Override
specifier|protected
parameter_list|<
name|T
parameter_list|>
name|Enumerator
argument_list|<
name|T
argument_list|>
name|executeQuery
parameter_list|(
name|QueryableImpl
argument_list|<
name|T
argument_list|>
name|queryable
parameter_list|)
block|{
return|return
literal|null
return|;
block|}
comment|/**      * Binds an expression to this query provider.      */
specifier|private
specifier|static
class|class
name|ExpressionQueryable
parameter_list|<
name|T
parameter_list|>
extends|extends
name|QueryableImpl
argument_list|<
name|T
argument_list|>
block|{
specifier|public
name|ExpressionQueryable
parameter_list|(
name|JdbcQueryProvider
name|jdbcQueryProvider
parameter_list|,
name|Type
name|elementType
parameter_list|,
name|Expression
name|expression
parameter_list|)
block|{
name|super
argument_list|(
name|jdbcQueryProvider
argument_list|,
name|elementType
argument_list|,
name|expression
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|JdbcQueryProvider
name|getProvider
parameter_list|()
block|{
return|return
operator|(
name|JdbcQueryProvider
operator|)
name|super
operator|.
name|getProvider
argument_list|()
return|;
block|}
block|}
block|}
end_class

begin_comment
comment|// End JdbcQueryProvider.java
end_comment

end_unit

