begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to you under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|adapter
operator|.
name|elasticsearch
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|util
operator|.
name|Closer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|http
operator|.
name|HttpHost
import|;
end_import

begin_import
import|import
name|com
operator|.
name|fasterxml
operator|.
name|jackson
operator|.
name|databind
operator|.
name|ObjectMapper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|client
operator|.
name|RestClient
import|;
end_import

begin_import
import|import
name|org
operator|.
name|elasticsearch
operator|.
name|common
operator|.
name|transport
operator|.
name|TransportAddress
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|rules
operator|.
name|ExternalResource
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Objects
import|;
end_import

begin_comment
comment|/**  * Used to initialize a single elastic node. For performance reasons (node startup costs),  * same instance is usually shared across multiple tests.  *  * This rule should be used as follows:  *<pre>  *  public class MyTest {  *&#64;ClassRule  *    public static final EmbeddedElasticsearchPolicy RULE = EmbeddedElasticsearchPolicy.create();  *  *&#64;BeforeClass  *    public static void setup() {  *       // ... populate instance  *    }  *  *&#64;Test  *    public void myTest() {  *      TransportAddress address = RULE.httpAddress();  *      // ....  *    }  *  }  *</pre>  * @see ExternalResource  */
end_comment

begin_class
class|class
name|EmbeddedElasticsearchPolicy
extends|extends
name|ExternalResource
block|{
specifier|private
specifier|final
name|EmbeddedElasticsearchNode
name|node
decl_stmt|;
specifier|private
specifier|final
name|ObjectMapper
name|mapper
decl_stmt|;
specifier|private
specifier|final
name|Closer
name|closer
decl_stmt|;
specifier|private
name|RestClient
name|client
decl_stmt|;
specifier|private
name|EmbeddedElasticsearchPolicy
parameter_list|(
name|EmbeddedElasticsearchNode
name|resource
parameter_list|)
block|{
name|this
operator|.
name|node
operator|=
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|resource
argument_list|,
literal|"resource"
argument_list|)
expr_stmt|;
name|this
operator|.
name|mapper
operator|=
operator|new
name|ObjectMapper
argument_list|()
expr_stmt|;
name|this
operator|.
name|closer
operator|=
operator|new
name|Closer
argument_list|()
expr_stmt|;
name|closer
operator|.
name|add
argument_list|(
name|node
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|protected
name|void
name|before
parameter_list|()
throws|throws
name|Throwable
block|{
name|node
operator|.
name|start
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|protected
name|void
name|after
parameter_list|()
block|{
name|closer
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
comment|/**    * Factory method to create this rule.    * @return managed resource to be used in unit tests    */
specifier|public
specifier|static
name|EmbeddedElasticsearchPolicy
name|create
parameter_list|()
block|{
return|return
operator|new
name|EmbeddedElasticsearchPolicy
argument_list|(
name|EmbeddedElasticsearchNode
operator|.
name|create
argument_list|()
argument_list|)
return|;
block|}
comment|/**    * Exposes Jackson API to be used for low-level ES.    * @return existing instance of ObjectMapper    */
name|ObjectMapper
name|mapper
parameter_list|()
block|{
return|return
name|mapper
return|;
block|}
comment|/**    * Low-level http rest client to elastic search    * @return current ES rest client    */
name|RestClient
name|restClient
parameter_list|()
block|{
if|if
condition|(
name|client
operator|!=
literal|null
condition|)
block|{
return|return
name|client
return|;
block|}
name|TransportAddress
name|address
init|=
name|httpAddress
argument_list|()
decl_stmt|;
name|RestClient
name|client
init|=
name|RestClient
operator|.
name|builder
argument_list|(
operator|new
name|HttpHost
argument_list|(
name|address
operator|.
name|getAddress
argument_list|()
argument_list|,
name|address
operator|.
name|getPort
argument_list|()
argument_list|)
argument_list|)
operator|.
name|build
argument_list|()
decl_stmt|;
name|closer
operator|.
name|add
argument_list|(
name|client
argument_list|)
expr_stmt|;
name|this
operator|.
name|client
operator|=
name|client
expr_stmt|;
return|return
name|client
return|;
block|}
comment|/**    * HTTP address for rest clients (can be ES native or any other).    * @return http address to connect to    */
name|TransportAddress
name|httpAddress
parameter_list|()
block|{
return|return
name|node
operator|.
name|httpAddress
argument_list|()
return|;
block|}
block|}
end_class

begin_comment
comment|// End EmbeddedElasticsearchPolicy.java
end_comment

end_unit

