begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to you under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|avatica
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|avatica
operator|.
name|proto
operator|.
name|Common
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Objects
import|;
end_import

begin_comment
comment|/**  * An enumeration that denotes the severity of a given unexpected state.  */
end_comment

begin_enum
specifier|public
enum|enum
name|AvaticaSeverity
block|{
comment|/**    * The severity of the outcome of some unexpected state is unknown.    */
name|UNKNOWN
argument_list|(
literal|0
argument_list|)
block|,
comment|/**    * The system has been left in an unrecoverable state as a result of an operation.    */
name|FATAL
argument_list|(
literal|1
argument_list|)
block|,
comment|/**    * The result of an action resulted in an error which the current operation cannot recover    * from. Clients can attempt to execute the operation again.    */
name|ERROR
argument_list|(
literal|2
argument_list|)
block|,
comment|/**    * The operation completed successfully but a message was generated to warn the client about    * some unexpected state or action.    */
name|WARNING
argument_list|(
literal|3
argument_list|)
block|;
specifier|private
specifier|final
name|int
name|value
decl_stmt|;
name|AvaticaSeverity
parameter_list|(
name|int
name|value
parameter_list|)
block|{
name|this
operator|.
name|value
operator|=
name|value
expr_stmt|;
block|}
specifier|public
name|int
name|getValue
parameter_list|()
block|{
return|return
name|value
return|;
block|}
specifier|public
name|Common
operator|.
name|Severity
name|toProto
parameter_list|()
block|{
switch|switch
condition|(
name|this
condition|)
block|{
case|case
name|UNKNOWN
case|:
return|return
name|Common
operator|.
name|Severity
operator|.
name|UNKNOWN_SEVERITY
return|;
case|case
name|FATAL
case|:
return|return
name|Common
operator|.
name|Severity
operator|.
name|FATAL_SEVERITY
return|;
case|case
name|ERROR
case|:
return|return
name|Common
operator|.
name|Severity
operator|.
name|ERROR_SEVERITY
return|;
case|case
name|WARNING
case|:
return|return
name|Common
operator|.
name|Severity
operator|.
name|WARNING_SEVERITY
return|;
default|default:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Unhandled Severity level: "
operator|+
name|this
argument_list|)
throw|;
block|}
block|}
specifier|public
specifier|static
name|AvaticaSeverity
name|fromProto
parameter_list|(
name|Common
operator|.
name|Severity
name|proto
parameter_list|)
block|{
switch|switch
condition|(
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|proto
argument_list|)
condition|)
block|{
case|case
name|UNKNOWN_SEVERITY
case|:
return|return
name|AvaticaSeverity
operator|.
name|UNKNOWN
return|;
case|case
name|FATAL_SEVERITY
case|:
return|return
name|AvaticaSeverity
operator|.
name|FATAL
return|;
case|case
name|ERROR_SEVERITY
case|:
return|return
name|AvaticaSeverity
operator|.
name|ERROR
return|;
case|case
name|WARNING_SEVERITY
case|:
return|return
name|AvaticaSeverity
operator|.
name|WARNING
return|;
default|default:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Unhandled protobuf Severity level: "
operator|+
name|proto
argument_list|)
throw|;
block|}
block|}
block|}
end_enum

begin_comment
comment|// End AvaticaSeverity.java
end_comment

end_unit

