begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to you under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|sql
operator|.
name|type
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|type
operator|.
name|RelDataType
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|calcite
operator|.
name|rel
operator|.
name|type
operator|.
name|RelDataTypeSystem
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|Lists
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|hamcrest
operator|.
name|core
operator|.
name|Is
operator|.
name|is
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertThat
import|;
end_import

begin_comment
comment|/**  * Test for {@link SqlTypeFactoryImpl}.  */
end_comment

begin_class
specifier|public
class|class
name|SqlTypeFactoryTest
block|{
annotation|@
name|Test
specifier|public
name|void
name|testLeastRestrictiveWithAny
parameter_list|()
block|{
name|Fixture
name|f
init|=
operator|new
name|Fixture
argument_list|()
decl_stmt|;
name|RelDataType
name|leastRestrictive
init|=
name|f
operator|.
name|typeFactory
operator|.
name|leastRestrictive
argument_list|(
name|Lists
operator|.
name|newArrayList
argument_list|(
name|f
operator|.
name|sqlBigInt
argument_list|,
name|f
operator|.
name|sqlAny
argument_list|)
argument_list|)
decl_stmt|;
name|assertThat
argument_list|(
name|leastRestrictive
operator|.
name|getSqlTypeName
argument_list|()
argument_list|,
name|is
argument_list|(
name|SqlTypeName
operator|.
name|ANY
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testLeastRestrictiveWithNumbers
parameter_list|()
block|{
name|Fixture
name|f
init|=
operator|new
name|Fixture
argument_list|()
decl_stmt|;
name|RelDataType
name|leastRestrictive
init|=
name|f
operator|.
name|typeFactory
operator|.
name|leastRestrictive
argument_list|(
name|Lists
operator|.
name|newArrayList
argument_list|(
name|f
operator|.
name|sqlBigInt
argument_list|,
name|f
operator|.
name|sqlInt
argument_list|)
argument_list|)
decl_stmt|;
name|assertThat
argument_list|(
name|leastRestrictive
operator|.
name|getSqlTypeName
argument_list|()
argument_list|,
name|is
argument_list|(
name|SqlTypeName
operator|.
name|BIGINT
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testLeastRestrictiveWithNullability
parameter_list|()
block|{
name|Fixture
name|f
init|=
operator|new
name|Fixture
argument_list|()
decl_stmt|;
name|RelDataType
name|leastRestrictive
init|=
name|f
operator|.
name|typeFactory
operator|.
name|leastRestrictive
argument_list|(
name|Lists
operator|.
name|newArrayList
argument_list|(
name|f
operator|.
name|sqlVarcharNullable
argument_list|,
name|f
operator|.
name|sqlAny
argument_list|)
argument_list|)
decl_stmt|;
name|assertThat
argument_list|(
name|leastRestrictive
operator|.
name|getSqlTypeName
argument_list|()
argument_list|,
name|is
argument_list|(
name|SqlTypeName
operator|.
name|ANY
argument_list|)
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|leastRestrictive
operator|.
name|isNullable
argument_list|()
argument_list|,
name|is
argument_list|(
literal|true
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testLeastRestrictiveWithNull
parameter_list|()
block|{
name|Fixture
name|f
init|=
operator|new
name|Fixture
argument_list|()
decl_stmt|;
name|RelDataType
name|leastRestrictive
init|=
name|f
operator|.
name|typeFactory
operator|.
name|leastRestrictive
argument_list|(
name|Lists
operator|.
name|newArrayList
argument_list|(
name|f
operator|.
name|sqlNull
argument_list|,
name|f
operator|.
name|sqlNull
argument_list|)
argument_list|)
decl_stmt|;
name|assertThat
argument_list|(
name|leastRestrictive
operator|.
name|getSqlTypeName
argument_list|()
argument_list|,
name|is
argument_list|(
name|SqlTypeName
operator|.
name|NULL
argument_list|)
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|leastRestrictive
operator|.
name|isNullable
argument_list|()
argument_list|,
name|is
argument_list|(
literal|true
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/** Sets up data needed by a test. */
specifier|private
specifier|static
class|class
name|Fixture
block|{
name|SqlTypeFactoryImpl
name|typeFactory
init|=
operator|new
name|SqlTypeFactoryImpl
argument_list|(
name|RelDataTypeSystem
operator|.
name|DEFAULT
argument_list|)
decl_stmt|;
specifier|final
name|RelDataType
name|sqlBigInt
init|=
name|typeFactory
operator|.
name|createTypeWithNullability
argument_list|(
name|typeFactory
operator|.
name|createSqlType
argument_list|(
name|SqlTypeName
operator|.
name|BIGINT
argument_list|)
argument_list|,
literal|false
argument_list|)
decl_stmt|;
specifier|final
name|RelDataType
name|sqlInt
init|=
name|typeFactory
operator|.
name|createTypeWithNullability
argument_list|(
name|typeFactory
operator|.
name|createSqlType
argument_list|(
name|SqlTypeName
operator|.
name|INTEGER
argument_list|)
argument_list|,
literal|false
argument_list|)
decl_stmt|;
specifier|final
name|RelDataType
name|sqlVarcharNullable
init|=
name|typeFactory
operator|.
name|createTypeWithNullability
argument_list|(
name|typeFactory
operator|.
name|createSqlType
argument_list|(
name|SqlTypeName
operator|.
name|VARCHAR
argument_list|)
argument_list|,
literal|true
argument_list|)
decl_stmt|;
specifier|final
name|RelDataType
name|sqlNull
init|=
name|typeFactory
operator|.
name|createTypeWithNullability
argument_list|(
name|typeFactory
operator|.
name|createSqlType
argument_list|(
name|SqlTypeName
operator|.
name|NULL
argument_list|)
argument_list|,
literal|false
argument_list|)
decl_stmt|;
specifier|final
name|RelDataType
name|sqlAny
init|=
name|typeFactory
operator|.
name|createTypeWithNullability
argument_list|(
name|typeFactory
operator|.
name|createSqlType
argument_list|(
name|SqlTypeName
operator|.
name|ANY
argument_list|)
argument_list|,
literal|false
argument_list|)
decl_stmt|;
block|}
block|}
end_class

begin_comment
comment|// End SqlTypeFactoryTest.java
end_comment

end_unit

